"""Paper-trading domain models — accounts, positions, orders, fills, NAV, checks.

A separate set of tables from the legacy ``accounts/positions/orders/fills`` mocks
so that the paper engine can use Float quantities and the same cost shape as the
research backtest (``BacktestCostConfig``).
"""

from sqlalchemy import Boolean, Float, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base_class import BaseModel


class PaperAccount(BaseModel):
    """Simulated trading account bound to a strategy version."""

    __tablename__ = "paper_accounts"

    name: Mapped[str] = mapped_column(String(128), nullable=False)
    owner_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    strategy_id: Mapped[str | None] = mapped_column(String(36), nullable=True, index=True)
    strategy_version_id: Mapped[str | None] = mapped_column(String(36), nullable=True, index=True)
    market: Mapped[str] = mapped_column(String(16), default="A")
    base_currency: Mapped[str] = mapped_column(String(8), default="CNY")
    initial_cash: Mapped[float] = mapped_column(Float, nullable=False)
    cash: Mapped[float] = mapped_column(Float, nullable=False)
    cost_config_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    inception_date: Mapped[str | None] = mapped_column(String(32), nullable=True)
    last_processed_date: Mapped[str | None] = mapped_column(String(32), nullable=True, index=True)
    peak_nav: Mapped[float | None] = mapped_column(Float, nullable=True)
    status: Mapped[str] = mapped_column(String(16), default="active", index=True)  # active / paused / closed


class PaperPosition(BaseModel):
    """Current paper-trading position per account/symbol."""

    __tablename__ = "paper_positions"
    __table_args__ = (
        UniqueConstraint("account_id", "symbol", name="uq_paper_positions_account_symbol"),
    )

    account_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    symbol: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    quantity: Mapped[float] = mapped_column(Float, default=0.0)
    avg_cost: Mapped[float] = mapped_column(Float, default=0.0)
    last_price: Mapped[float | None] = mapped_column(Float, nullable=True)
    market_value: Mapped[float] = mapped_column(Float, default=0.0)
    weight: Mapped[float] = mapped_column(Float, default=0.0)


class PaperOrder(BaseModel):
    """Order generated by the EOD signal engine, pending → filled / rejected."""

    __tablename__ = "paper_orders"

    account_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    strategy_id: Mapped[str | None] = mapped_column(String(36), nullable=True, index=True)
    trade_date: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    symbol: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    side: Mapped[str] = mapped_column(String(8), nullable=False)  # buy / sell
    target_weight: Mapped[float] = mapped_column(Float, default=0.0)
    target_quantity: Mapped[float] = mapped_column(Float, default=0.0)
    filled_quantity: Mapped[float] = mapped_column(Float, default=0.0)
    status: Mapped[str] = mapped_column(String(16), default="pending", index=True)
    # pending / approved / filled / partial / rejected / canceled
    reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    rejection_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    requires_approval: Mapped[bool] = mapped_column(Boolean, default=False)


class PaperFill(BaseModel):
    """Filled portion of a PaperOrder."""

    __tablename__ = "paper_fills"

    order_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    account_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    trade_date: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    symbol: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    side: Mapped[str] = mapped_column(String(8), nullable=False)
    quantity: Mapped[float] = mapped_column(Float, nullable=False)
    price: Mapped[float] = mapped_column(Float, nullable=False)
    amount: Mapped[float] = mapped_column(Float, nullable=False)
    commission: Mapped[float] = mapped_column(Float, default=0.0)
    stamp_tax: Mapped[float] = mapped_column(Float, default=0.0)
    slippage: Mapped[float] = mapped_column(Float, default=0.0)
    total_cost: Mapped[float] = mapped_column(Float, default=0.0)
    net_cash_flow: Mapped[float] = mapped_column(Float, default=0.0)


class PaperNavPoint(BaseModel):
    """Daily NAV snapshot of a paper account."""

    __tablename__ = "paper_nav_points"
    __table_args__ = (
        UniqueConstraint("account_id", "trade_date", name="uq_paper_nav_account_date"),
    )

    account_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    trade_date: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    nav: Mapped[float] = mapped_column(Float, nullable=False)
    cash: Mapped[float] = mapped_column(Float, nullable=False)
    market_value: Mapped[float] = mapped_column(Float, default=0.0)
    daily_return: Mapped[float | None] = mapped_column(Float, nullable=True)
    drawdown: Mapped[float | None] = mapped_column(Float, nullable=True)


class PaperPreTradeCheck(BaseModel):
    """Pre-trade check outcome for a PaperOrder."""

    __tablename__ = "paper_pre_trade_checks"

    order_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    account_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    rule: Mapped[str] = mapped_column(String(64), nullable=False)
    current_value: Mapped[float] = mapped_column(Float, default=0.0)
    limit_value: Mapped[float] = mapped_column(Float, default=0.0)
    status: Mapped[str] = mapped_column(String(16), default="pass")  # pass / warn / fail
    note: Mapped[str | None] = mapped_column(Text, nullable=True)


class PaperRiskBreach(BaseModel):
    """Risk breach raised against a paper account."""

    __tablename__ = "paper_risk_breaches"

    account_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    trade_date: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    rule: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    severity: Mapped[str] = mapped_column(String(16), default="medium")
    detail: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[str] = mapped_column(String(16), default="ongoing", index=True)  # ongoing / acknowledged / resolved
